kind: pipeline
type: docker
name: build

trigger:
  event:
    - push
    - tag
    - pull_request

steps:
  - name: tidy
    image: golang:1.19.2
    commands:
      - go mod tidy
      - git diff --exit-code -- go.mod go.sum
    depends_on: [clone]

  - name: lint
    image: golang:1.19.2
    commands:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.0
      - export PATH=$PATH:~/go/bin
      - golangci-lint run -v -E gofmt -D typecheck
    depends_on: [clone]

  - name: vet
    image: golang:1.19.2
    commands:
      - go vet -race ./...
    depends_on: [clone]

  - name: build
    image: golang:1.19.2
    commands:
      - go build -race .
    depends_on: [clone]

  - name: gosec
    image: securego/gosec:2.13.1
    commands:
      - gosec -tests ./...
    depends_on: [clone]
---
kind: pipeline
type: docker
name: test

trigger:
  event:
    - push
    - tag

steps:
  - name: test
    image: golang:1.19.2
    commands:
      - go test -v -race ./...
